# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cpp_prim
else:
    import _cpp_prim

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cpp_prim.delete_SwigPyIterator

    def value(self):
        return _cpp_prim.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cpp_prim.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cpp_prim.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cpp_prim.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cpp_prim.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cpp_prim.SwigPyIterator_copy(self)

    def next(self):
        return _cpp_prim.SwigPyIterator_next(self)

    def __next__(self):
        return _cpp_prim.SwigPyIterator___next__(self)

    def previous(self):
        return _cpp_prim.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cpp_prim.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cpp_prim.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cpp_prim.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cpp_prim.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cpp_prim.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cpp_prim.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cpp_prim.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _cpp_prim:
_cpp_prim.SwigPyIterator_swigregister(SwigPyIterator)

class intvector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_prim.intvector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_prim.intvector___nonzero__(self)

    def __bool__(self):
        return _cpp_prim.intvector___bool__(self)

    def __len__(self):
        return _cpp_prim.intvector___len__(self)

    def __getslice__(self, i, j):
        return _cpp_prim.intvector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cpp_prim.intvector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cpp_prim.intvector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cpp_prim.intvector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cpp_prim.intvector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cpp_prim.intvector___setitem__(self, *args)

    def pop(self):
        return _cpp_prim.intvector_pop(self)

    def append(self, x):
        return _cpp_prim.intvector_append(self, x)

    def empty(self):
        return _cpp_prim.intvector_empty(self)

    def size(self):
        return _cpp_prim.intvector_size(self)

    def swap(self, v):
        return _cpp_prim.intvector_swap(self, v)

    def begin(self):
        return _cpp_prim.intvector_begin(self)

    def end(self):
        return _cpp_prim.intvector_end(self)

    def rbegin(self):
        return _cpp_prim.intvector_rbegin(self)

    def rend(self):
        return _cpp_prim.intvector_rend(self)

    def clear(self):
        return _cpp_prim.intvector_clear(self)

    def get_allocator(self):
        return _cpp_prim.intvector_get_allocator(self)

    def pop_back(self):
        return _cpp_prim.intvector_pop_back(self)

    def erase(self, *args):
        return _cpp_prim.intvector_erase(self, *args)

    def __init__(self, *args):
        _cpp_prim.intvector_swiginit(self, _cpp_prim.new_intvector(*args))

    def push_back(self, x):
        return _cpp_prim.intvector_push_back(self, x)

    def front(self):
        return _cpp_prim.intvector_front(self)

    def back(self):
        return _cpp_prim.intvector_back(self)

    def assign(self, n, x):
        return _cpp_prim.intvector_assign(self, n, x)

    def resize(self, *args):
        return _cpp_prim.intvector_resize(self, *args)

    def insert(self, *args):
        return _cpp_prim.intvector_insert(self, *args)

    def reserve(self, n):
        return _cpp_prim.intvector_reserve(self, n)

    def capacity(self):
        return _cpp_prim.intvector_capacity(self)
    __swig_destroy__ = _cpp_prim.delete_intvector

# Register intvector in _cpp_prim:
_cpp_prim.intvector_swigregister(intvector)

class intvectorvector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_prim.intvectorvector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_prim.intvectorvector___nonzero__(self)

    def __bool__(self):
        return _cpp_prim.intvectorvector___bool__(self)

    def __len__(self):
        return _cpp_prim.intvectorvector___len__(self)

    def __getslice__(self, i, j):
        return _cpp_prim.intvectorvector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cpp_prim.intvectorvector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cpp_prim.intvectorvector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cpp_prim.intvectorvector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cpp_prim.intvectorvector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cpp_prim.intvectorvector___setitem__(self, *args)

    def pop(self):
        return _cpp_prim.intvectorvector_pop(self)

    def append(self, x):
        return _cpp_prim.intvectorvector_append(self, x)

    def empty(self):
        return _cpp_prim.intvectorvector_empty(self)

    def size(self):
        return _cpp_prim.intvectorvector_size(self)

    def swap(self, v):
        return _cpp_prim.intvectorvector_swap(self, v)

    def begin(self):
        return _cpp_prim.intvectorvector_begin(self)

    def end(self):
        return _cpp_prim.intvectorvector_end(self)

    def rbegin(self):
        return _cpp_prim.intvectorvector_rbegin(self)

    def rend(self):
        return _cpp_prim.intvectorvector_rend(self)

    def clear(self):
        return _cpp_prim.intvectorvector_clear(self)

    def get_allocator(self):
        return _cpp_prim.intvectorvector_get_allocator(self)

    def pop_back(self):
        return _cpp_prim.intvectorvector_pop_back(self)

    def erase(self, *args):
        return _cpp_prim.intvectorvector_erase(self, *args)

    def __init__(self, *args):
        _cpp_prim.intvectorvector_swiginit(self, _cpp_prim.new_intvectorvector(*args))

    def push_back(self, x):
        return _cpp_prim.intvectorvector_push_back(self, x)

    def front(self):
        return _cpp_prim.intvectorvector_front(self)

    def back(self):
        return _cpp_prim.intvectorvector_back(self)

    def assign(self, n, x):
        return _cpp_prim.intvectorvector_assign(self, n, x)

    def resize(self, *args):
        return _cpp_prim.intvectorvector_resize(self, *args)

    def insert(self, *args):
        return _cpp_prim.intvectorvector_insert(self, *args)

    def reserve(self, n):
        return _cpp_prim.intvectorvector_reserve(self, n)

    def capacity(self):
        return _cpp_prim.intvectorvector_capacity(self)
    __swig_destroy__ = _cpp_prim.delete_intvectorvector

# Register intvectorvector in _cpp_prim:
_cpp_prim.intvectorvector_swigregister(intvectorvector)


def run_algorithm(graph):
    return _cpp_prim.run_algorithm(graph)


